version: "3.8"

services:
  backend-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend-api
    container_name: backend-api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend-api/.env.development
    volumes:
      - ./backend-api:/backend-api
      - /backend-api/node_modules

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.development
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend-api
