version: "3.3"

services:
  backend-api:
    build:
      dockerfile: Dockerfile.prod
      context: ./
    container_name: backend-api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./.env.production
    volumes:
      - ./:/backend-api
      - /node_modules

  ui:
    build:
      dockerfile: Dockerfile.prod
      context: ./ui
    container_name: ui
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./ui/.env.production
    volumes:
      - ./ui/nginx.conf:/etc/nginx/sites-available/default
      - /var/certs/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - backend-api
