version: "3.8"

services:
  backend-api:
    build:
      dockerfile: Dockerfile.prod
      context: ./backend-api
    container_name: backend-api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend-api/.env.production
    volumes:
      - ./backend-api:/backend-api
      - /backend-api/node_modules

  client:
    build:
      dockerfile: Dockerfile.prod
      context: ./client
    container_name: client
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./client/.env.production
    volumes:
      - ./client/nginx.conf:/etc/nginx/sites-available/default
      - /var/certs/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - backend-api
