version: "3.3"

services:
  dice-api:
    build:
      dockerfile: Dockerfile.prod
      context: ./dice-api
    container_name: dice-api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./dice-api/.env.production
    volumes:
      - ./dice-api:/dice-api
      - /dice-api/node_modules

  dice-client:
    build:
      dockerfile: Dockerfile.prod
      context: ./dice-client
    container_name: dice-client
    ports:
      - "8080:80"
      - "443:443"
    env_file:
      - ./dice-client/.env.production
    volumes:
      - ./dice-client/nginx.conf:/etc/nginx/sites-available/default
      - /var/certs/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - dice-api
