version: "3.3"

services:
  dice-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./dice-api
    container_name: dice-api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./dice-api/.env.development
    volumes:
      - ./dice-api:/dice-api
      - /dice-api/node_modules

  dice-client:
    build:
      dockerfile: Dockerfile.dev
      context: ./dice-client
    container_name: dice-client
    ports:
      - "3000:3000"
    env_file:
      - ./dice-client/.env.development
    volumes:
      - ./dice-client:/dice-client
      - /dice-client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - dice-api
