version: "3.3"

services:
  dice-api:
    build:
      dockerfile: Dockerfile.prod
      context: ./dice-api
    container_name: dice-api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./dice-api/.env.production
    volumes:
      - ./dice-api:/dice-api
      - /dice-api/node_modules
